ALTER TABLE user_preferences
  ADD COLUMN IF NOT EXISTS protein_target_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS calories_target_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS carbs_target_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS fats_target_enabled BOOLEAN NOT NULL DEFAULT TRUE;